config/routes.rb
Ga::Application.routes.draw do

  get "enrolments/create"

# ROOT
  root to: 'events#index'

# USERS
  get '/login', to: 'sessions#new'
  resources :sessions, only: [:create, :destroy]
  resources :users
  get 'events/:id/enrol', to: "events#enrol", as: 'enrol'
  get 'account', to: 'users#account', as: 'account'
  get 'far_koff', to: 'sessions#destroy'

# EVENTS
get 'my_events', to: 'events#my_events', as: 'my_events'
get 'new_booking/:id', to: 'events#clone', as: 'new_booking'
get 'events/:id/bookings', to: 'events#bookings', as: 'bookings'
resources :events do
    collection do
      match 'search', to: 'events#search', via: [:get, :post], as: :search
    end
    # get 'page/:page', action: :index, on: :collection
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :event_image, :name, :price, :creator_id, :description, :start_time, :start_date, :end_date, :end_time, :address, :postcode

# ASSOCIATIONS
  belongs_to :creator, class_name: 'User'
  has_many :bookings
  has_many :locations, through: :bookings
  has_many :enrolments
  has_many :users, through: :enrolments

# CARRIERWAVE
  mount_uploader :event_image, EventImageUploader


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @q = Event.search(params[:q])
    @events = @q.result(distinct: true)
    if @q.result.empty?
      flash[:error] = "No matches"
    end
  end

  def my_events
    @q = Event.where(creator_id: current_user.id).search(params[:q])
    @events = @q.result(distinct: true)
    if @q.result.empty?
      flash[:error] = "No matches"
    end
  end

  def bookings
    @event = Event.find(params[:id])
    @events = Event.scoped
  end

  def search
    index
    render :index
  end

  def show
    @user = current_user
    @event = Event.find(params[:id])
  end

  # USER ENROLS ON EVENT
  def enrol
    @event = Event.find(params[:id])
    @enrolment = Enrolment.create(event_id: @event.id, user_id: current_user.id, enrolment_date: DateTime.now.to_date, enrolment_status: 'Active', payment_status: 'pending')
    redirect_to event_path
  end

  # USER UNROLS FROM EVENT
  def destroy_enrol
    @event = Event.find(params[:id])
    @enrolment = Enrolment.destroy(event_id: @event.id, user_id: current_user.id, enrolment_date: DateTime.now.to_date, enrolment_status: 'Active', payment_status: 'pending')
    redirect_to account_path
  end

  # CREATE NEW BOOKING FOR EVENT
  def clone
    @event = Event.find(params[:id])
    @event = @event.dup
    @event.save
    render 'new'
  end

  def new
    @event = Event.new
  end

  # CREATE NEW EVENT
  def create
    @event = Event.new(params[:event])
    # DEFINING EVENT CREATOR
    @event.creator=current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
     @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_path }
      format.json { head :no_content }
    end
  end


  def enrolment_method
    @enrolment = Enrolment.new([:user])
    if @enrolment.save
      redirect_to root_path
    else
      render 'new'
    end
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_booking.html.erb
<%= form_for(@event) do |f| %>
 <!-- ERROR HANDLING  -->
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- FORM -->
  <div class="field">
    <%= f.label 'name:' %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label 'price:' %>
    <%= f.text_field :price %>
  </div>
  <br>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :event_image %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_events.html.erb
<% if flash %>
  <%= flash[:error] %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>

<!-- ERROR HANDLING -->
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- FORM -->
  <div class="field">
    <%= f.label 'name:' %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label 'description:' %>
    <%= f.text_area :description %>
  </div>
  <br>
    <div class="field">
    <%= f.label 'start time:' %>
    <%= f.time_select :start_time %>
  </div>
  <br>
    <div class="field">
    <%= f.label 'start date:' %>
    <%= f.date_select  :start_date %>
  </div>
  <br>
    <div class="field">
    <%= f.label 'end time:' %>
    <%= f.time_select :end_time %>
  </div>
  <br>
    <div class="field">
    <%= f.label 'end date:' %>
    <%= f.date_select :end_date %>
  </div>
  <br>
  <div class="field">
    <%= f.label 'address:' %>
    <%= f.text_field :address %>
  </div>
  <br>
  <div class="field">
    <%= f.label 'postcode:' %>
    <%= f.text_field :postcode %>
  </div>
  <br>
  <div class="field">
    <%= f.label 'price:' %>
    <%= f.text_field :price %>
  </div>
  <br>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :event_image %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/bookings.html.erb
<!-- PARTNER BOOKING SECTION -->

<% if can? :manage, Event %>


<table>
  <tr>
    <th>Address</th>
    <th>Postcode</th>
    <th>Start time</th>
    <th>Start date</th>
    <th>End time</th>
    <th>End date</th>
    <th>Delete booking</th>
  </tr>
  <% @events.where('events.name = ?', @event.name).each do |event| %>
    <tr>
      <td><%= event.address%></td>
      <td><%= event.postcode%></td>
      <td><%= event.start_time%></td>
      <td><%= event.start_date%></td>
      <td><%= event.end_time%></td>
      <td><%= event.end_date%></td>
      <td> <%= link_to 'delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <%= link_to 'New booking', new_booking_path(event) %>
    </tr>
  <% end %>
</table>


<% end %>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render 'events' %>

<!-- RENDERS BOXES ON EVENT PAGE -->
<div class='quad_view_container'>

<% @events.each do |event| %>

  <div class='quad_view_box'>

    <div class='quad_box_image'>
      <%= image_tag event.event_image.detail.url, size: '150x150' %>
    </div>

    <div class='quad_box_text'>
      <h4><%= link_to event.name, event %></h4>
      <!-- THIS CUTS DESCRIPTION TO 70 CHARACTERS -->
      <p><%= event.description.split(" ").each_with_object("") {|x,ob| break ob unless (ob.length + " ".length + x.length <= 70);ob << (" " + x)}.strip %></p>
      <p><%= event.price %></p>
    </div>
    <% if can? :manage, event %>
    <%= link_to 'Edit', edit_event_path(event) %>
    <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

  </div><!-- end_of_ quod_box_biew -->
<% end %>
</div><!-- end of quad_view_container -->

app/views/events/my_events.html.erb
<%= render 'events' %>

<table>
  <tr>
    <th>Image</th>
    <th>Event</th>
    <th>Price</th>
    <th>Bookings</th>
    <th>Edit</th>
    <th>Destroy</th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <% if can? :manage, Event %>
    <td> <%= image_tag event.event_image.thumb.url %></td>
    <td><%= link_to event.name, event %></td>
    <td><%= event.price %></td>
    <td><%= link_to 'Bookings', bookings_path(id: event.id) %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>

    <% end %>
  </tr>
<% end %>
</table>

<br />

<br />

app/views/events/new.html.erb
<h1>Create event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/new_booking.html.erb
<h1>Add booking</h1>

<%= render 'form' %>

<%= link_to 'Back', my_events_path %>

app/views/events/show.html.erb
<div class='show_body'>
<h1><%= @event.name %></h1>


<!-- EVENT INFORMATION -->
<!-- event.description put in description -->
<%= image_tag @event.event_image.url %><br>
<%= @event.description %><br>


<!-- VIEW USERS CURRENTLY ENROLLED -->
<% if can? :manage, Event %>
<br>CURRENTLY ENROLLED PARTICIPANTS
  <% @event.users.each do |user| %>
    <br><%= user.name %>
  <% end %>
<% end %><br>


<!-- ENROL -->
<% unless can? :manage, Event %>
  <%= link_to 'Enrol', enrol_path(@event.id) %>
<% end %>
<%= link_to 'Back', events_path %>
</div>