config/routes.rb
Ga::Application.routes.draw do

  get "enrolments/create"

# ROOT
  root to: 'events#index'

# USERS
  get '/login', to: 'sessions#new'
  resources :sessions, only: [:create, :destroy]
  resources :users
  get 'events/:id/enrol', to: "events#enrol", as: 'enrol'
  get 'account', to: 'users#account', as: 'account'
  get 'far_koff', to: 'sessions#destroy'

# EVENTS
get 'my_events', to: 'events#my_events', as: 'my_events'
get 'new_booking/:id', to: 'events#clone', as: 'new_booking'
get 'events/:id/bookings', to: 'events#bookings', as: 'bookings'
resources :events do
    collection do
      match 'search', to: 'events#search', via: [:get, :post], as: :search
    end
    # get 'page/:page', action: :index, on: :collection
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ga</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="container">
  <header>
    <%= link_to image_tag('logo.png', size: '160x120'), '/' %>
  </header>

  <% flash.each do |name, message| %>
   <div class="flash-message flash-message-<%= name %>">
    <%= message %>
   </div>
  <% end %>

  <%= yield %>

  <div class="footer"><!-- footer section -->

    <div class="login"> <!-- login section -->

      <!-- user signup, login, logout secion  -->
      <% if current_user %>
        <%= current_user.email %>
      <%= link_to 'logout', session_path(session), method: :delete, data: {confirm: 'are you sure?' } %>
      <% else %>
        <% if params[:action] != 'new' && params[:controller] != 'users'  %>
          <%= link_to 'Sign up', new_user_path %>
         <%= link_to 'Login', login_path %>
       <% else %>
         <%= link_to 'Login', login_path %>
       <% end %>
      <% end %>

      <!-- event, my event, account links -->
      <%= link_to 'Events', events_path %>
      <% if can? :create, Event %>
        <%= link_to 'New Event', new_event_path %>
      <% end %>
      <% if current_user != nil %>
        <%= link_to 'My Events', my_events_path %>
        <%= link_to 'Account', account_path %>
      <% end %>
      <% if can? :manage, :all %>
        <%= link_to 'Admin', users_path %>
      <% end %>


     <!-- search form -->
     <%= search_form_for @q, url: search_events_path, html: {method: :post} do |f| %>
        <%= f.text_field :name_cont %>
        <%= f.submit %>
    <% end %>

    </div><!-- closes login -->

    <div class='footer_image'>
      <%= image_tag('footer2.png', size: '900x350') %>
    </div>

  </div><!-- closes footer -->
</div><!-- closes container -->
</body>
</html>